spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness
    driver-class-name: org.postgresql.Driver
    username: masteruser
    password: 1616

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
#  mustache:
#    prefix: classpath:/templates/
#    suffix: .html
#    charset: UTF-8
# Mustache 관련 설정은 주석 처리합니다.


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
